name: C/C++ CI Drishya

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Compile C Program
      run: gcc Logic.c -o Logic
    - name: Run Program
      run: ./Logic
    - name: Notify Success 
      if: success() 
      run: |
       curl -H "Title: CI Success" \ 
            -d "C program compiled and executed successfully." \ 
            https://ntfy.sh/log310807

    - name: Notify Failure 
      if: failure() 
      run: |
       curl -H "Title: CI Failed" \ 
            -d "Build or execution failed in C/C++ CI pipeline." \ 
            https://ntfy.sh/log310807